### ISSUE TITLE
Error "No rule to make target" when compiling and generating BEMRosetta.out

### ISSUE THREAD

**Issue by hoangmyvang** [izabala123/BEMRosetta#1]
Hi. 

I've pulled BEMRosetta to my PC, and there is an error when I compile and generate the BEMRosetta.out. 

Like below screenshot:
![image](https://user-images.githubusercontent.com/50905158/58157766-36a7f080-7ca3-11e9-8895-178449551f2f.png)

Can you help me check this error out? 
Many Thanks. 
My Vang.

**Comment by izabala123** [comment]
Hi My

I am sorry, I had a problem packaging the Linux version. I think it is fixed now.
In addition this version opens AQWA files.

Best regards
Iñaki

**Comment by izabala123** [comment]
Hi My

Any news?

**Comment by izabala123** [comment]
A continuous delivery infrastructure has been deployed, so all changes are compiled in Linux and Windows before being submitted.
This way, this kind of errors are virtually removed.
