### ISSUE TITLE
[21042] Frequency 0.209000 not found

### ISSUE THREAD

**Issue by robeche** [izabala123/BEMRosetta#2]
Dear Iñaki,

First of all thanks for your contribution at OpenOre. Basically you made exactly what i was needing!

Well, i have an AQWA file which i try to open in Rosetta but i get the following error:
[21042] Frequency 0.209000 not found

In the LIS file a frequency of 0.20944rad/s is defined, which refers to the 30s period. I don´t understand why rosetta is looking for the 0.209 frequency. 
![2019-09-04_15-21-59](https://user-images.githubusercontent.com/45792405/64258626-dd00c480-cf27-11e9-940f-42f8f8473430.png)

My intention was to open this AQWA generated file and save it into NEMOH or WAMIT format. 

Kind regards

Roberto

**Comment by izabala123** [comment]
Hi Roberto. Could you upload the file? I will check it.

**Comment by robeche** [comment]
Hello Iñaki and thanks for your answer. The truth is that i can´t upload the file as it has not been generated by me or my company. 

I´ve been investigating on the issue, and I was wondering if the reason could be that it has been generated with the latest release of Ansys Aqwa. Besides this, I´ve tried with another simulation software which replies that this version of Ansys Aqwa is not supported. Do you think this could be the issue as well?

Kind regards

**Comment by izabala123** [comment]
Hi Roberto. It is a pity not to have the file.
BEMRosetta complains because in line 21042 reads the frequency 0.209, that has not been registered previously in the file (more that "not found" is "unknown").
Could you send the frequencies you define (from, to, delta)? 
If the delta between frequencies is lower or equal to 0.001, this could be an issue.

**Comment by robeche** [comment]
Hi there again!
Looks like these guys from Ansys have some kind of issue when formatting numbers with fprintf, I have seen the frequencies written with 5, 4 and 3 decimals in the same LIS file... I fix the 0.209 which correspond to a period of 30s... Now i will fix the others...

Thanks a lot for your help! I will tell you if it works once I finished with the rest

Roberto

**Comment by izabala123** [comment]
Hi Roberto. That's interesting.
Taking into account this, I would upload a new version today with some improvements and a filter for AQWA so that,  two frequencies are different if their difference is >= 0.001.
Thank you for your report.

**Comment by robeche** [comment]
Yes, finally it worked out, I had to manually adjust all the decimal formatting but finally i was able to convert the file into wamit format. 
But now, a new problem arised... The software where i want to import this hydrodynamic data (Bladed) allows me to import a wamit file but it is asking me for an .out file. The Rosetta application only creates files .1, .2, .4 and .hst. And the hst is empty. Is this correct.

**Comment by izabala123** [comment]
Hi Roberto. That's interesting.
Taking into account this, I would upload a new version today with some improvements and a filter for AQWA so that,  two frequencies are different if their difference is >= 0.001.
Thank you for your report.

**Comment by izabala123** [comment]
The binaries and source have been updated. Please check if they handle this problem.
