### ISSUE TITLE
During make on Linux

### ISSUE THREAD

**Issue by saltynexus** [izabala123/BEMRosetta#5]
make: *** No rule to make target 'ScatterDraw/Unpedantic.h', needed by '_out/BEMRosetta/BEMRosetta_cl/GCC-Gcc-Linux-Main-Posix-Shared/main.o'.  Stop.

**Comment by izabala123** [comment]
Right, compiling has to be fixed. Compiling procedure will change.

**Comment by izabala123** [comment]
Compiling procedure has changed. Please check [this](https://github.com/izabala123/BEMRosetta/tree/master/install) ant tell me if it works well for your distro. Thank you.

**Comment by izabala123** [comment]
There have been no comments for some time, so we can close it. In case of new problems we can open a new issue.
